import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRef, useState } from 'react';
import Image from 'next/image';

import trash from '../img/trash.svg'

export default function Home() {
  const taskRef = useRef(null)
  const [task, setTask] = useState('');
  const [storeTask, setStoreTask] = useState([]);
  const [err, setErr] = useState('');

  // catch one task
  const updateTask = (e) => {
    setTask(e.target.value)
    setErr('')
  }

  // append single task to storeTask array on submit
  const addTask = (e) =>{
    e.preventDefault();

    const singleTask = [...task]
    if (task !== '') {
      if(singleTask.indexOf(task) === -1 ){
        console.log('duplicate not found');
        setStoreTask([...storeTask, task])
      }else{
        setErr("Sorry, " + task + " Has been added")
      }
    }else{
      setErr('Can not add empty task')
    }
    taskRef.current.value = ''
  }
  return (
    <>
    <Head>
      <title>Todoist</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.container}>
      <form className={styles.form}>
        <input type="text" ref={taskRef} onChange={(e) => updateTask(e)}/>
        <button onClick={(e) => addTask(e)}>Add</button>
      </form>
      <span className={styles.error}>{ err }</span>
      {
        storeTask.map(data => (
          <div className={styles.task}key={data}>
            <p >{ data }</p>
              <Image src={trash} height={50} width={50} alt="trash task" onClick={() => console.log(data)}/>
          </div>
        ))
      }
    </div>
    </>
  )
}
